INFO - 2025-02-23 05:34:06 --> CSRF token verified.
DEBUG - 2025-02-23 05:34:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-23 05:34:46 --> CSRF token verified.
INFO - 2025-02-23 06:06:37 --> CSRF token verified.
INFO - 2025-02-23 06:08:07 --> CSRF token verified.
CRITICAL - 2025-02-23 06:58:55 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "sidebar.php"
[Method: GET, Route: records]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('sidebar.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('sidebar', [], true)
 3 APPPATH\Controllers\Records.php(10): view('sidebar', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
INFO - 2025-02-23 07:00:53 --> CSRF token verified.
ERROR - 2025-02-23 08:13:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#9 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-02-23 08:13:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: records]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `records`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
ERROR - 2025-02-23 08:14:01 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#9 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-02-23 08:14:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: records]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `records`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
ERROR - 2025-02-23 08:14:11 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#9 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-02-23 08:14:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: records]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `records`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
ERROR - 2025-02-23 08:14:15 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#9 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-02-23 08:14:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: records]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `records`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
ERROR - 2025-02-23 08:14:28 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#9 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-02-23 08:14:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: records]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `records`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
ERROR - 2025-02-23 08:15:34 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#9 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-02-23 08:15:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: records]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `records`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
ERROR - 2025-02-23 08:15:39 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'dashboard', 3306, '', 0)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#9 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\codeignit4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\codeignit4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\codeignit4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\codeignit4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\codeignit4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\codeignit4\app\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(933): App\Controllers\Records->index()
#7 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
#8 D:\xampp\htdocs\codeignit4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\codeignit4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\codeignit4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\codeignit4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\codeignit4\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-02-23 08:15:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: records]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `records`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Records.php(9): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Records->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Records))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\codeignit4\\public\\index.php')
